### ISSUE TITLE
Secret, ConfigMap and OB are not deleted when OBC is deleted

### ISSUE THREAD

**Issue by guymguym** [kube-object-storage/lib-bucket-provisioner#134]
```
kubectl create obc baba ...
kubectl get obc,ob,secret,cm
kubectl delete obc baba
kubectl get obc,ob,secret,cm
# ob, secret, cm are still there...
```
This seems to be because they have a finalizer and the provisioner is not removing it...

**Comment by guymguym** [comment]
I was trying to automate the cleanup when I uninstall the noobaa operator but due to #133  I can't even identify the secrets and configmaps that were created by my provisioner after the obc is gone.

Seems like finalizer is winning over blockOwnerDeletion and the OBC is deleted even though the objects referencing it are still "alive" since they are in a deletion process...

**Comment by guymguym** [comment]
Note: I couldn't reproduce it when the provisioner is running.

**Comment by jeffvance** [comment]
I can't dup this and perhaps #138 will improve the situation? Can we close this?

**Comment by guymguym** [comment]
Yes. Thanks for double checking.
