### ISSUE TITLE
`error` return value is always nil

### ISSUE THREAD

**Issue by copejon** [kube-object-storage/lib-bucket-provisioner#135]
No process within [NewProvisioner()](https://github.com/kube-object-storage/lib-bucket-provisioner/blob/5b3f4e3b90edc8c914edb04fb5dc0dfee5f9f0d4/pkg/provisioner/manager.go#L69) generates and error; the function will only ever return `nil`.   

Let's remove the `error` return value from the function so consumers don't end up writing unnecessary error checks.

**Comment by guymguym** [comment]
It's really a non-issue, but still I don't think it's the right thing to do.
Making such changes for saving the error checks that are probably just occurring in a single location in the code of every provider is not worth removing the error from the main initialization API call of a library. This just limits the flexibility of the library to improve. If providers don't want to handle errors explicitly in initialization they can panic or fatal. CC @travisn

**Comment by travisn** [comment]
Agreed that it's a very minor issue, but philosophically speaking... 

If an API has no need to return an error, why return a placeholder that will always be nil? It will require unnecessary error handling by the caller. 

With golang an API can change over time. Clients that need to update to the latest API would update their vendoring and then change their calls accordingly. So there is nothing preventing the API from changing if an error condition is added in the future.

**Comment by guymguym** [comment]
I philosophically don't mind it either way :)

BTW this is a SEMVER MAJOR change.

**Comment by guymguym** [comment]
I'm removing the "bug" label

**Comment by copejon** [comment]
Those are all pretty compelling reasons not to mess with it right now, closing.
