### ISSUE TITLE
Adding options to set quota in OBC CRD

### ISSUE THREAD

**Issue by thotz** [kube-object-storage/lib-bucket-provisioner#193]
There was request in rook to [support quota](https://github.com/rook/rook/issues/5274), and worked a bit on that wrt [obc](https://github.com/rook/rook/pull/5674). Currently make use of `AddtionalConfig` CR. Is worth to add generic CRs to handle to quota and add to library.

Please share your thoughts, @jeffvance @guymguym @copejon

**Comment by jeffvance** [comment]
@thotz I just added a [comment](https://github.com/rook/rook/issues/5274#issuecomment-648957757) to the quota issue. 
We also have a bucket API [KEP](https://github.com/kubernetes/enhancements/pull/1383) where getting your quota feedback would be valuable. As of now, I don't think we need a separate CR to manage bucket quotas. I prefer integrating bucket quotas into the new design where applicable, and using the existing CR quota feature.

**Comment by thotz** [comment]
closing this issue based above comment
