### ISSUE TITLE
Fix provision check for empty OB returned

### ISSUE THREAD

**Issue by BlaineEXE** [kube-object-storage/lib-bucket-provisioner#203]
See discussion on comment: https://github.com/kube-object-storage/lib-bucket-provisioner/pull/201#discussion_r546008824

**Comment by BlaineEXE** [comment]
We needed to do a similar thing in Rook and had to use an external library (github.com/google/go-cmp/cmp) to "diff" objects.

https://github.com/rook/rook/blob/ad24990473a876ba014b11ef61f8d63d46190ec0/pkg/operator/ceph/cluster/predicate.go#L124-L154

I would propose that if we want to check for equality to empty, this must look like
```go
cmp.Diff(v1alpha1.ObjectBucket{}, *ob)
```

**Comment by BlaineEXE** [comment]
@travisn is there a reason we used `cmp.Diff` in Rook and not apiequality.Semantic.DeepEqual? 
https://stupefied-goodall-e282f7.netlify.app/contributors/devel/api_changes/#update-the-semantic-comparisons
https://github.com/kubernetes/apimachinery/blob/0ca7b349afd234e3376e550db2392f41236be77b/pkg/api/equality/semantic.go#L27-L49

**Comment by travisn** [comment]
@leseb IIRC you implemented the diff check? I don't recall the details.

**Comment by BlaineEXE** [comment]
I don't think I did. @leseb do you recall?

**Comment by leseb** [comment]
@travisn you actually did add it long ago I remember since I requested it. We use it to get the CR diff changes when the CR is updated. We don't actually use it for equality. We might as well use DeepEqual unless the type cannot be "deep equaled".

**Comment by travisn** [comment]
Oh did I do that? :) I was thinking there was another change after mine, oh well. We really just need to know if there is any difference so we know to update the pod spec, then print the diff to the log.
