### ISSUE TITLE
consider an /internal dir in repo

### ISSUE THREAD

**Issue by jeffvance** [kube-object-storage/lib-bucket-provisioner#80]
```
Use of /internal
The /internal package is woefully underused. I recommend both binaries and libraries take advantage of /internal to hide public functions that aren’t intended to be imported. Hiding your public import space also makes clearer which packages users should import and where to look for useful logic.
```
From: https://medium.com/@cep21/aspects-of-a-good-go-library-7082beabb403

**Comment by copejon** [comment]
The article is referring to the use of the `internal` pkg of golang, rather than defining our own.  I learned the hard way that the compiler won't allow an `internal` pkg to be defined.

**Comment by copejon** [comment]
+1

**Comment by guymguym** [comment]
I don't think there's a need to keep an open issue for that.
Can we close @jeffvance ?

**Comment by jeffvance** [comment]
Yes it can be closed. Was just a suggestion for consideration.
